settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from django.conf.urls import url
from django.urls import re_path as url 
from django.conf.urls.static import static
from django.views.static import serve 
from django.contrib.auth import views as auth_views
from main.views import (
    IndexView, 
    SuporteView,
    ColoradoShowView,
    
    MaquinasView,    
    ServicosView,
    PecasView,
    ImplementosView,
    AgriculturaView,
    ConsorcioView,
    SegurosView,
    
    AcessoriosView,
    BrinquedosView,
    UtensiliosView,
    
    ContatoCampanhaView,
    ContatoCollectionView
)

urlpatterns = [
    #URLs estáticas
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
	url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    
    #URLs iniciais
    path('admin', admin.site.urls),
    path('', IndexView, name="home"),
    path('suporte', SuporteView, name="suporte"),
    path('coloradoshow', ColoradoShowView, name="coloradoshow"),
    
    #URLs das Campanhas
    path('campanhas/maquinas-agricolas', MaquinasView, name="maquinas"),
    path('campanhas/servicos', ServicosView, name="servicos"),
    path('campanhas/pecas-e-acessorios', PecasView, name="pecas"),
    path('campanhas/implementos-multimarcas', ImplementosView, name="implementos"),
    path('campanhas/agricultura-de-precisao', AgriculturaView, name="agricultura"),
    path('campanhas/consorcio-nacional-john-deere', ConsorcioView, name="consorcio"),
    path('campanhas/seguros', SegurosView, name="seguro"),
    
    #URLs das Collections
    path('collections/roupas-e-acessorios', AcessoriosView, name="acessorios"),
    path('collections/miniaturas-e-brinquedos', BrinquedosView, name="brinquedos"),
    path('collections/utensilios', UtensiliosView, name="utensilios"),
    
    
    #URLs dos Leads
    path('campanhas/cadastrar-contato/<id_campanha>', ContatoCampanhaView, name="lead_campanha"),
    path('collections/cadastrar-contato/<id_collection>', ContatoCollectionView, name="lead_collection"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Configuração dos campos Admin
admin.site.site_header = 'Hotsite Colorado Máquinas'
admin.site.site_title = 'Hotsite Colorado Máquinas'
admin.site.index_title = 'Administração'
admin.empty_value_display = '**Empty**'

main/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponse
from unidecode import unidecode
from django.core.validators import FileExtensionValidator
from ckeditor.fields import RichTextField


#Grupos de classes
GRUPO = [
    ('Campanha', 'Campanha'),
    ('Collection', 'Collection'),
]


#Função para source no cadastro de imagem dos grupos
def ImagemClasse(request, filename):
    src = 'classes/{filename}'.format(filename=unidecode(filename))
    return src


#Função para source no cadastro de imagem da campanha
def ImagemCampanha(request, filename):
    src = 'campanhas/{filename}'.format(filename=unidecode(filename))
    return src


#Função para source no cadastro de imagem da collection
def ImagemCollection(request, filename):
    src = 'collections/{filename}'.format(filename=unidecode(filename))
    return src


#Função para source no cadastro de imagem dos grupos
def ImagemConecta(request, filename):
    src = 'conecta/{filename}'.format(filename=unidecode(filename))
    return src


#Função para source no cadastro de imagem da colorado show
def ImagemColorado(request, filename):
    src = 'coloradoshow/{filename}'.format(filename=unidecode(filename))
    return src


# main_classes (Classes - Grupos Cadastrais)
class Classes(models.Model):
    nome                    = models.CharField(max_length=128, verbose_name="Nome")
    descricao               = RichTextField(null=True, blank=True, verbose_name="Descrição")
    url                     = models.CharField(max_length=128, null=True, blank=True, verbose_name="URL (Não alterar!)")
    grupo                   = models.CharField(max_length=64, choices=GRUPO, verbose_name="Grupo")
    status                  = models.BooleanField(default=True, verbose_name="Status")
    imagem                  = models.ImageField(upload_to=ImagemClasse, verbose_name="Imagem (450x500)", validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    
    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name = "Classe"
        verbose_name_plural = "5.0 - Classes" 


# main_campanha (Campanhas)
class Campanha(models.Model):
    campanha                 = models.CharField(max_length=128, verbose_name="Campanha")
    grupo                    = models.ForeignKey(Classes, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Classe")
    descricao                = RichTextField(null=True, blank=True, verbose_name="Descrição")
    informacoes              = RichTextField(null=True, blank=True, verbose_name="Informações Adicionais")
    local                    = models.CharField(max_length=128, null=True, blank=True, verbose_name="Local")
    contato1                 = models.CharField(max_length=128, null=True, blank=True, verbose_name="Celular")
    contato2                 = models.CharField(max_length=128, null=True, blank=True, verbose_name="Telefone")
    keyword                  = models.CharField(max_length=128, verbose_name="SEO")
    status                   = models.BooleanField(default=True, verbose_name="Status")
    imagem                   = models.ImageField(upload_to=ImagemCampanha, verbose_name="Imagem (450x500)", validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    
    def __str__(self):
        return self.campanha
    
    class Meta:
        verbose_name = "Campanha"
        verbose_name_plural = "5.1 - Campanhas" 


# main_collection (Collections)
class Collection(models.Model):
    collection               = models.CharField(max_length=128, verbose_name="Collection")
    grupo                    = models.ForeignKey(Classes, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Classe")
    descricao                = RichTextField(null=True, blank=True, verbose_name="Descrição")
    informacoes              = RichTextField(null=True, blank=True, verbose_name="Informações Adicionais")
    local                    = models.CharField(max_length=128, null=True, blank=True, verbose_name="Local")
    contato1                 = models.CharField(max_length=128, null=True, blank=True, verbose_name="Celular")
    contato2                 = models.CharField(max_length=128, null=True, blank=True, verbose_name="Telefone")
    keyword                  = models.CharField(max_length=128, verbose_name="SEO")
    status                   = models.BooleanField(default=True, verbose_name="Status")
    imagem                   = models.ImageField(upload_to=ImagemCollection, verbose_name="Imagem (450x500 ou Superior)", validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.collection
    
    class Meta:
        verbose_name = "Collection"
        verbose_name_plural = "5.1 - Collections" 
        

# main_contatocampanha (LEAD das Campanhas)
class ContatoCampanha(models.Model):
    campanha                 = models.ForeignKey(Campanha, on_delete=models.CASCADE, null=True, blank=True)
    nome                     = models.CharField(max_length=64, verbose_name="Nome Contato")
    email                    = models.EmailField(max_length=64, verbose_name="Email Contato")
    assunto                  = models.CharField(max_length=128, verbose_name="Assunto Contato")
    mensagem                 = models.TextField(max_length=512, verbose_name="Mensagem Contato")
    numero                   = models.CharField(max_length=32, null=True, blank=True, verbose_name="Numero Contato")
    data_contato             = models.DateTimeField(auto_now_add=True, verbose_name="Data Contato")
    
    def __str__(self):
        return self.nome + ' - ' + str(self.campanha)
    
    class Meta:
        verbose_name = "Lead Campanha"
        verbose_name_plural = "5.2 - Lead Campanhas" 
        

# main_contatocollection (LEAD das Collections)
class ContatoCollection(models.Model):
    collection               = models.ForeignKey(Collection, on_delete=models.CASCADE, null=True, blank=True)
    nome                     = models.CharField(max_length=64, verbose_name="Nome Contato")
    email                    = models.EmailField(max_length=64, verbose_name="Email Contato")
    assunto                  = models.CharField(max_length=128, verbose_name="Assunto Contato")
    mensagem                 = models.TextField(max_length=512, verbose_name="Mensagem Contato")
    numero                   = models.CharField(max_length=32, null=True, blank=True, verbose_name="Numero Contato")
    data_contato             = models.DateTimeField(auto_now_add=True, verbose_name="Data Contato")
    
    def __str__(self):
        return self.nome + ' - ' + str(self.collection)
    
    class Meta:
        verbose_name = "Lead Collection"
        verbose_name_plural = "5.2 - Lead Collections" 
        
        
# main_keyword (SEO)
class Keyword(models.Model):
    keyword                  = models.CharField(max_length=128, verbose_name="SEO")
    descricao                = models.CharField(max_length=128, null=True, blank=True, verbose_name="Descrição SEO")
    status                   = models.BooleanField(default=True, verbose_name="Status")

    def __str__(self):
        return self.keyword
    
    class Meta:
        verbose_name = "SEO"
        verbose_name_plural = "1.0 - SEO" 
        

# main_conecta (App Conecta)
class Conecta(models.Model):
    publicacao               = models.CharField(max_length=128, verbose_name="Publicação App Conecta")
    descricao                = RichTextField(null=True, blank=True, verbose_name="Descrição")
    status                   = models.BooleanField(default=False, verbose_name="Status")
    imagem                   = models.ImageField(upload_to=ImagemConecta, verbose_name="Imagem (420x520)", validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.publicacao
    
    class Meta:
        verbose_name = "App Conecta"
        verbose_name_plural = "2.0 - App Conecta" 


# main_coloradoshow (Colorado Show)
class ColoradoShow(models.Model):
    publicacao               = models.CharField(max_length=128, verbose_name="Publicação Colorado Show")
    descricao                = RichTextField(null=True, blank=True, verbose_name="Descrição")
    status                   = models.BooleanField(default=False, verbose_name="Status")
    imagem                   = models.ImageField(upload_to=ImagemColorado, verbose_name="Imagem (420x520)", validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])

    def __str__(self):
        return self.publicacao
    
    class Meta:
        verbose_name = "Colorado Show"
        verbose_name_plural = "2.0 - Colorado Show" 
        

# main_suporte (Cadastros de Suporte)
class Suporte(models.Model):
    suporte               = models.CharField(max_length=128, verbose_name="Suporte")
    telefone              = models.CharField(max_length=128, null=True, blank=True, verbose_name="Telefone")
    celular               = models.CharField(max_length=128, null=True, blank=True, verbose_name="Celular")
    email                 = models.EmailField(max_length=64, null=True, blank=True, verbose_name="Email")

    def __str__(self):
        return self.suporte
    
    class Meta:
        verbose_name = "Canal de Suporte"
        verbose_name_plural = "3.0 - Canais de Suporte" 
        
        
# main_midia (Videos do YouTube)
class Midia(models.Model):
    midia                    = models.CharField(max_length=128, verbose_name="Nome da Mídia")
    url                      = models.URLField(max_length=512, verbose_name="URL da Mídia")
    descricao                = RichTextField(max_length=128, null=True, blank=True, verbose_name="Descrição da Mídia")

    def __str__(self):
        return self.midia
    
    class Meta:
        verbose_name = "Webserie"
        verbose_name_plural = "4.0 - Webseries" 

main/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms import modelformset_factory, BaseFormSet, formset_factory
from main.models import (
    Campanha,
    Collection,
    ContatoCampanha,
    ContatoCollection,
    Midia,
    Keyword
)


#Form para o contate-nos na home, sem cadastro em banco de dados, apenas envio de email
class FormContato(forms.Form):
    nome        = forms.CharField(required=True)
    email       = forms.EmailField(required=True)
    assunto     = forms.CharField(required=True)
    mensagem    = forms.CharField(widget=forms.Textarea, required=True)
    

#form do detalhamento de vagas
class FormContatoCampanha(forms.ModelForm):
    class Meta:
        model = ContatoCampanha
        fields = '__all__'   
        exclude = ['campanha', 'data_contato']

    
#form do detalhamento de vagas
class FormContatoCollection(forms.ModelForm):
    class Meta:
        model = ContatoCollection
        fields = '__all__'
        exclude = ['collection', 'data_contato']

main/templates/leads/lead_campanha.html
{% extends 'index.html' %}
{% block content %}
{% load static %}
{% include '../mensagem.html' %}
<div id="fullpage" class="fullpage-default">
    <div class="section animated-row" data-section="slide06">
        <div class="section-inner">
            <div class="row justify-content-center mt-5 mt-md-0">
                <div class="col-md-7 wide-col-laptop">
                    <div class="title-block animate" data-animate="fadeInUp">
                        <h3>Confirme seu interesse aqui</h3>
                        <p>Entraremos em contato em breve</p>
                    </div>
                    <div class="contact-section">
                        <div class="row">
                            <div class="col animate" data-animate="fadeInUp">
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col">
                                            <div class="input-field">
                                                <input type="text" class="form-control" name="nome" id="id_nome" required placeholder="Nome">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="input-field">
                                                <input type="text" class="form-control" name="numero" id="id_numero" required placeholder="Celular">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-field">
                                        <input type="email" class="form-control" name="email" id="id_email" required placeholder="Email">
                                    </div>
                                    <div class="input-field">
                                        <input type="text" class="form-control" name="assunto" id="id_assunto" required placeholder="Assunto">
                                    </div>
                                    <div class="input-field">
                                        <textarea onkeyup="countChar(this)" class="form-control" name="mensagem" id="id_mensagem" required placeholder="Mensagem"></textarea>
                                        <small class="d-flex align-items-start">Caracteres restantes: <a id="charNum">512</a></small>
                                    </div>
                                    <button class="btn" type="submit">Cadastrar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/leads/lead_collection.html
{% extends 'index.html' %}
{% block content %}
{% load static %}
{% include '../mensagem.html' %}
<div id="fullpage" class="fullpage-default">
    <div class="section animated-row" data-section="slide06">
        <div class="section-inner">
            <div class="row justify-content-center mt-5 mt-md-0">
                <div class="col-md-7 wide-col-laptop">
                    <div class="title-block animate" data-animate="fadeInUp">
                        <h3>Confirme seu interesse aqui</h3>
                        <p>Entraremos em contato em breve</p>
                    </div>
                    <div class="contact-section">
                        <div class="row">
                            <div class="col animate" data-animate="fadeInUp">
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col">
                                            <div class="input-field">
                                                <input type="text" class="form-control" name="nome" id="id_nome" required placeholder="Nome">
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="input-field">
                                                <input type="text" class="form-control" name="numero" id="id_numero" required placeholder="Celular">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="input-field">
                                        <input type="email" class="form-control" name="email" id="id_email" required placeholder="Email">
                                    </div>
                                    <div class="input-field">
                                        <input type="text" class="form-control" name="assunto" id="id_assunto" required placeholder="Assunto">
                                    </div>
                                    <div class="input-field">
                                        <textarea onkeyup="countChar(this)" class="form-control" name="mensagem" id="id_mensagem" required placeholder="Mensagem"></textarea>
                                        <small class="d-flex align-items-start">Caracteres restantes: <a id="charNum">512</a></small>
                                    </div>
                                    <button class="btn" type="submit">Cadastrar</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}